import Link from 'next/link';
import { useState, type ReactNode } from 'react';
import { useStore } from '@/store/useStore';
import { usePersona } from '@/lib/persona';
import { PERSONA_LABELS, SIM_SOURCES } from './types';
import { formatRatio, formatUSD } from '@/lib/format';
import { computeBudgetStatus } from '@/lib/budgetStatus';
import { SnapshotButton } from '@/executive/SnapshotButton';
import { useSimulationAccess } from './SimulationProvider';

export function WorkspacePage() {
  const sim = useStore(s => s.simulation);
  const access = useSimulationAccess();
  const busy = useStore(s => s.simulationBusy);
  const run = useStore(s => s.simulationCommand);
  const selectWorkload = useStore(s => s.select);
  const { persona, setPersona } = usePersona();
  const [chosen, setChosen] = useState('');
  const [amount, setAmount] = useState('');
  const [source, setSource] = useState('all');
  if (!sim) return <div className="p-8"><h1 className="text-2xl">Customer workflow</h1><p className="mt-3 text-sub">{access?.loading ? 'Restoring your workspace…' : 'Sign in with a simulated customer identity to continue.'}</p><Link href="/simulation" className="mt-5 inline-block text-unit underline">Choose a simulated identity</Link></div>;
  const { state, session } = sim;
  const identity = session.identity;
  const technical = identity.persona === 'technical';
  const w = state.workloads.find(x => x.id === chosen) ?? state.workloads[0];
  const b = state.budgets.find(x => x.workload_id === w.id)!;
  const costs = state.ledger.reduce((n, r) => n + r.cents, 0) / 100;
  const value = state.workloads.reduce((n, x) => n + x.value.total_value, 0);
  const forecast = computeBudgetStatus(w, b, new Date(state.asOf));
  const rows = state.ledger.filter(r => source === 'all' || r.source === source);
  const viewSteps = persona === 'technical'
    ? [['Connectors', '/connectors', 'Import the next fixture once; check the source totals.'], ['Workloads', '/workloads', 'Inspect budget, models, governance and alerts.'], ['Findings', '/', 'Request a change, then implement it after approval.']]
    : persona === 'procurement'
    ? [['Model comparison', '/workloads', 'Compare model rates at the same volume; review value assumptions.'], ['Decision queue', '#decisions', 'Fund a budget and approve a requested change.'], ['Reports', '/reports', 'Download a cost report and preview its delivery.']]
    : [['Overview', '/overview', 'Review spend, business value and forecast risk.'], ['Decision queue', '#decisions', 'Review and authorize a proposed change.'], ['Reports', '/reports', 'Share a snapshot of the saved customer workspace.']];
  return <div className="h-full overflow-y-auto px-4 py-6 sm:px-8"><div className="mx-auto max-w-6xl space-y-7">
    <header><p className="text-xs uppercase tracking-widest text-unit">{identity.tenant} · simulated customer</p><h1 className="mt-2 text-2xl font-semibold">Cost tracking workspace</h1><p className="mt-2 text-sm text-sub">Billing period: June 2026. Data through June 25. Business value is a seeded assumption; savings remain projections until measured.</p>
      <label className="mt-4 inline-flex items-center gap-3 text-sm">View <select className="sim-input" value={persona} onChange={e => setPersona(e.target.value as typeof persona)}>{Object.entries(PERSONA_LABELS).map(([p, name]) => <option key={p} value={p}>{name}</option>)}</select></label><p className="mt-2 text-xs text-sub">Changing the view changes the presentation. Permissions remain those of your signed-in {PERSONA_LABELS[identity.persona]} identity.</p>
    </header>
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Recorded cost · USD" value={formatUSD(costs)} /><Metric label="Assumed business value" value={formatUSD(value)} /><Metric label="Value / cost" value={formatRatio(value / costs)} /></div>
    <div className="grid gap-3 md:grid-cols-3">{viewSteps.map(([title, href, detail], i) => <Link key={title} href={href} onClick={() => selectWorkload(w.id)} className="rounded-lg border border-edge bg-deep p-5 hover:border-sub"><p className="text-xs text-dim">0{i + 1}</p><h2 className="mt-2 font-semibold">{title}</h2><p className="mt-2 text-sm text-sub">{detail}</p></Link>)}</div>
    <section className="rounded border border-edge bg-deep p-5"><h2 className="text-lg font-semibold">Business outcome accountability</h2><p className="mt-2 text-sm text-sub">Assign an owner, compare pre-AI performance, review value evidence and full costs, then record a business decision.</p><Link className="mt-4 inline-block text-unit underline" href="/outcomes">Measure initiative outcomes</Link></section>
    <section className="rounded border border-edge bg-deep p-5"><h2 className="text-lg font-semibold">Embedded agent reviews</h2><p className="mt-2 text-sm text-sub">Queue an evidence review, process it with a recoverable lease, and review the proposed next steps across roles.</p><Link className="mt-4 inline-block text-unit underline" href="/agent-workflows">Open agent workflows</Link></section>
    <Section title="Source reconciliation"><p className="mb-4 text-sm text-sub">Synthetic ledger charges reconcile to the same workload totals shown on every view. Re-importing a fixture leaves costs unchanged.</p><div className="grid gap-3 sm:grid-cols-3">{SIM_SOURCES.map(s => <div key={s} className="rounded border border-edge p-4"><h3 className="font-semibold uppercase">{s}</h3><p className="mt-2 font-mono">{formatUSD(state.ledger.filter(r => r.source === s).reduce((n, r) => n + r.cents, 0) / 100)}</p><p className="mt-1 text-xs text-sub">Portfolio value ratio {formatRatio(value / costs)}</p><p className="mt-2 text-xs text-sub">{state.imports.includes(`fixture-june-v1:${s}`) ? 'Fixture imported · replay safe' : 'Seed imported · next fixture available'}</p><button className="sim-button mt-3" disabled={busy || !technical} onClick={() => void run({ type: 'sync', source: s })}>Import {s.toUpperCase()} fixture</button></div>)}</div>{!technical && <p className="mt-3 text-xs text-sub">A Technical identity imports data. You can review the saved results here.</p>}</Section>
    <Section title="Budget and forecast"><div className="flex flex-wrap items-center gap-3"><label>Workload <select aria-label="Workflow workload" className="sim-input ml-2" value={w.id} onChange={e => { setChosen(e.target.value); setAmount(''); selectWorkload(e.target.value); }}>{state.workloads.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><Link className="text-unit underline" href="/workloads" onClick={() => selectWorkload(w.id)}>Inspect workload tabs</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric label="Recorded cost / assumed value" value={`${formatUSD(w.costs.monthly_spend)} / ${formatRatio(w.value.value_ratio)}`} /><Metric label="Monthly budget" value={formatUSD(w.costs.monthly_budget)} /><Metric label="Projected month end" value={formatUSD(forecast.monthly.projectedEom)} /></div><p className="mt-3 text-sm text-sub">Projected monthend uses the saved budget and simulated billing history. Forecasts are estimates.</p><form className="mt-4 flex flex-wrap items-end gap-3" onSubmit={e => { e.preventDefault(); void run({ type: 'budget', workloadId: w.id, amount: Number(amount) }); }}><label className="text-sm">New monthly budget (USD)<input required aria-label="New monthly budget" type="number" min="0.01" max="1000000000" step="0.01" className="sim-input mt-1 block" value={amount} onChange={e => setAmount(e.target.value)} disabled={technical || busy} /></label><button className="sim-button" disabled={technical || busy || !amount}>Save budget</button></form>{technical && <p className="mt-2 text-xs text-sub">Executive and Procurement identities can fund budgets.</p>}</Section>
    <section id="decisions"><Section title="Change decisions"><p className="mb-4 text-sm text-sub">Request → approval → simulated application of business-hours scheduling. Requests do not execute a cloud change. Historical charges stay unchanged.</p><div className="space-y-3">{state.workloads.map(x => { const change = state.changes[x.id]; return <div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-edge p-4"><div><h3 className="font-medium">{x.name}</h3><p className="mt-1 text-xs text-sub">{formatUSD(x.costs.monthly_spend)} · {formatRatio(x.value.value_ratio)} value · {change ? `${change.ref} · ${change.status}` : 'No change requested'}</p>{change?.approvedBy && <p className="mt-1 text-xs text-sub">Approved by {change.approvedBy}</p>}</div><button className="sim-button" disabled={busy || (!change ? !technical : change.status === 'requested' ? technical : change.status === 'approved' ? !technical : true)} onClick={() => void run({ type: !change ? 'request-change' : change.status === 'requested' ? 'approve-change' : 'apply-change', workloadId: x.id })}>{!change ? 'Request change' : change.status === 'requested' ? 'Approve change' : change.status === 'approved' ? 'Apply simulated change' : 'Applied in simulation'}</button></div>; })}</div></Section></section>
    <Section title="Recorded charges"><div className="mb-3 flex flex-wrap items-center gap-3"><label>Source <select className="sim-input ml-2" value={source} onChange={e => setSource(e.target.value)}><option value="all">All sources</option>{SIM_SOURCES.map(s => <option key={s}>{s}</option>)}</select></label><span className="text-sm text-sub">{rows.length} entries · {formatUSD(rows.reduce((n, r) => n + r.cents, 0) / 100)} · {formatRatio(value / costs)} portfolio value</span></div><div className="overflow-x-auto"><table className="sim-table"><caption className="text-left text-xs text-sub">Most recent 20 entries. All entries are included in totals.</caption><thead><tr><th>Date</th><th>Workload</th><th>Source</th><th>Cost · USD</th><th>Value ratio</th></tr></thead><tbody>{rows.slice(-20).reverse().map(r => <tr key={r.id}><td>{r.date}</td><td>{state.workloads.find(x => x.id === r.workloadId)?.name}</td><td>{r.source.toUpperCase()}</td><td>{formatUSD(r.cents / 100)}</td><td>{formatRatio(state.workloads.find(x => x.id === r.workloadId)!.value.value_ratio)}</td></tr>)}</tbody></table></div></Section>
    <Section title="Audit trail"><p className="mb-3 text-sm text-sub">Actions record the server-verified identity and are committed together with the workspace change.</p>{state.audit.length ? <ol className="space-y-2 text-sm">{state.audit.slice(-12).reverse().map(a => <li key={a.id} className="border-b border-edge py-2"><span className="text-sub">{a.at} · {a.actor}</span><br />{a.action} · {a.target}</li>)}</ol> : <p className="text-sm text-sub">No changes yet. Import a fixture or request a change to start the trail.</p>}</Section>
    <div className="flex flex-wrap items-center justify-between gap-4"><Link className="text-unit underline" href="/reports">Open Reports and delivery simulation</Link><SnapshotButton /></div>
  </div></div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded border border-edge bg-deep p-4"><p className="text-xs text-sub">{label}</p><p className="mt-2 font-mono text-lg">{value}</p></div>; }
function Section({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-lg border border-edge bg-deep p-4 sm:p-6"><h2 className="mb-4 text-lg font-semibold">{title}</h2>{children}</section>; }
